name: Focal

on:
  push:
    paths: 'build_boost_focal.yaml'

jobs:
  build:

    runs-on: ubuntu-latest
    container: ubuntu:focal
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v1
    - name: install ansible
      run: |
        apt-get update
        apt-get install software-properties-common ansible python-apt -y
    - name: run ansible
      run : ansible-playbook ./build_boost_focal.yaml
